background = #0c1010
foreground = #d5f4e3

cursor-color = #e7fc7c
cursor-text = #0c1010

selection-background = #272d2d
selection-foreground = #d5f4e3

# Black
palette = 0=#272d2d
# Dark Red
palette = 1=#ffa9d2
# Dark Green
palette = 2=#96e497
# Dark Yellow
palette = 3=#e7fc7c
# Dark Blue
palette = 4=#c3eed9
# Dark Magenta
palette = 5=#b2b8f6
# Dark Cyan
palette = 6=#7ad49f
# Light Gray
palette = 7=#b2e5cd

# Gray
palette = 8=#51796d
# Red
palette = 9=#ffa9d2
# Green
palette = 10=#96e497
# Yellow
palette = 11=#e7fc7c
# Blue
palette = 12=#c3eed9
# Magenta
palette = 13=#c3c8ff
# Cyan
palette = 14=#8ee4b2
# White
palette = 15=#d5f4e3
