background = #1c2020
foreground = #c1efd5

cursor-color = #dbee7a
cursor-text = #1c2020

selection-background = #333939
selection-foreground = #c1efd5

# Black
palette = 0=#333939
# Dark Red
palette = 1=#f08cb4
# Dark Green
palette = 2=#80c980
# Dark Yellow
palette = 3=#dbee7a
# Dark Blue
palette = 4=#abe7ca
# Dark Magenta
palette = 5=#a2b0e0
# Dark Cyan
palette = 6=#59bf84
# Light Gray
palette = 7=#9bdebe

# Gray
palette = 8=#51796d
# Red
palette = 9=#f08cb4
# Green
palette = 10=#80c980
# Yellow
palette = 11=#dbee7a
# Blue
palette = 12=#abe7ca
# Magenta
palette = 13=#b6bee0
# Cyan
palette = 14=#75d69e
# White
palette = 15=#c1efd5
