background = #f8f9f9
foreground = #2b3b33

cursor-color = #a8ba33
cursor-text = #f8f9f9

selection-background = #e3e8e8
selection-foreground = #2b3b33

# Black
palette = 0=#425953
# Dark Red
palette = 1=#cb4c7c
# Dark Green
palette = 2=#3f9640
# Dark Yellow
palette = 3=#a8ba33
# Dark Blue
palette = 4=#51796d
# Dark Magenta
palette = 5=#7062b8
# Dark Cyan
palette = 6=#15874d
# Light Gray
palette = 7=#e3e8e8

# Gray
palette = 8=#51796d
# Red
palette = 9=#cb4c7c
# Green
palette = 10=#3f9640
# Yellow
palette = 11=#a8ba33
# Blue
palette = 12=#51796d
# Magenta
palette = 13=#8074bd
# Cyan
palette = 14=#009a52
# White
palette = 15=#f8f9f9
