background = #1c2020
foreground = #c1efd5

cursor-color = #e7fc7c
cursor-text = #1c2020

selection-background = #333939
selection-foreground = #c1efd5

# Black
palette = 0=#333939
# Dark Red
palette = 1=#ffa9d2
# Dark Green
palette = 2=#96e497
# Dark Yellow
palette = 3=#e7fc7c
# Dark Blue
palette = 4=#abe7ca
# Dark Magenta
palette = 5=#b2b8f6
# Dark Cyan
palette = 6=#7ad49f
# Light Gray
palette = 7=#9bdebe

# Gray
palette = 8=#51796d
# Red
palette = 9=#ffa9d2
# Green
palette = 10=#96e497
# Yellow
palette = 11=#e7fc7c
# Blue
palette = 12=#abe7ca
# Magenta
palette = 13=#c3c8ff
# Cyan
palette = 14=#8ee4b2
# White
palette = 15=#c1efd5
