background = #dfe5ec
foreground = #0e1217

cursor-color = #19b168
cursor-text = #dfe5ec

selection-background = #b8bec5
selection-foreground = #0e1217

# Black
palette = 0=#0e1217
# Dark Red
palette = 1=#fb80aa
# Dark Green
palette = 2=#11a22f
# Dark Yellow
palette = 3=#f29520
# Dark Blue
palette = 4=#1c989e
# Dark Magenta
palette = 5=#fb4583
# Dark Cyan
palette = 6=#11a22f
# Light Gray
palette = 7=#757b81

# Gray
palette = 8=#43484e
# Red
palette = 9=#fb80aa
# Green
palette = 10=#11a22f
# Yellow
palette = 11=#f29520
# Blue
palette = 12=#1c989e
# Magenta
palette = 13=#6390fa
# Cyan
palette = 14=#19b168
# White
palette = 15=#b8bec5
