[metadata]
author = "Black Atom Industries"
name = "Black Atom — Facility ∷ Dimmed Light"

[colors]
foreground = "#2b3b33"
background = "#eaf0f0"
cursor_bg = "#a8ba33"
cursor_border = "#a8ba33"
cursor_fg = "#eaf0f0"
selection_bg = "#d2d9d9"
selection_fg = "#2b3b33"
split = "#a8ba33"
compose_cursor = "#cb4c7c"
scrollbar_thumb = "#669a84"

ansi = [
  "#425953", # black
  "#b54567", # dark_red
  "#358636", # dark_green
  "#d7a537", # dark_yellow
  "#517a65", # dark_blue
  "#7062b8", # dark_magenta
  "#15874d", # dark_cyan
  "#d2d9d9" # light_gray
]

brights = [
  "#476a5f", # gray
  "#cb4c7c", # red
  "#3f9640", # green
  "#a8ba33", # yellow
  "#476a5f", # blue
  "#8074bd", # magenta
  "#009a52", # cyan
  "#eaf0f0" # white
]

[colors.tab_bar]
inactive_tab_edge = "#dee4e4"
background = "#eaf0f0"

[colors.tab_bar.active_tab]
fg_color = "#eaf0f0"
bg_color = "#a8ba33"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#eaf0f0"
bg_color = "#77a494"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#eaf0f0"
bg_color = "#d2d9d9"

[colors.tab_bar.new_tab]
fg_color = "#eaf0f0"
bg_color = "#3f9640"

[colors.tab_bar.new_tab_hover]
fg_color = "#eaf0f0"
bg_color = "#d2d9d9"
intensity = "Bold"
