[metadata]
author = "Black Atom Industries"
name = "Black Atom — Facility ∷ Dimmed Dark"

[colors]
foreground = "#c1efd5"
background = "#1c2020"
cursor_bg = "#dbee7a"
cursor_border = "#dbee7a"
cursor_fg = "#1c2020"
selection_bg = "#333939"
selection_fg = "#c1efd5"
split = "#dbee7a"
compose_cursor = "#f08cb4"
scrollbar_thumb = "#91bcad"

ansi = [
  "#333939", # black
  "#eb7aa8", # dark_red
  "#5dba5d", # dark_green
  "#e9b565", # dark_yellow
  "#91bcad", # dark_blue
  "#a2b0e0", # dark_magenta
  "#59bf84", # dark_cyan
  "#9bdebe" # light_gray
]

brights = [
  "#51796d", # gray
  "#f08cb4", # red
  "#80c980", # green
  "#dbee7a", # yellow
  "#abe7ca", # blue
  "#b6bee0", # magenta
  "#75d69e", # cyan
  "#c1efd5" # white
]

[colors.tab_bar]
inactive_tab_edge = "#131717"
background = "#1c2020"

[colors.tab_bar.active_tab]
fg_color = "#1c2020"
bg_color = "#dbee7a"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#1c2020"
bg_color = "#51796d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#1c2020"
bg_color = "#242a2a"

[colors.tab_bar.new_tab]
fg_color = "#1c2020"
bg_color = "#80c980"

[colors.tab_bar.new_tab_hover]
fg_color = "#1c2020"
bg_color = "#242a2a"
intensity = "Bold"
