[metadata]
author = "Black Atom Industries"
name = "Black Atom — Facility ∷ Dark"

[colors]
foreground = "#d5f4e3"
background = "#0c1010"
cursor_bg = "#e2f776"
cursor_border = "#e2f776"
cursor_fg = "#0c1010"
selection_bg = "#272d2d"
selection_fg = "#d5f4e3"
split = "#e2f776"
compose_cursor = "#f08cb4"
scrollbar_thumb = "#91bcad"

ansi = [
  "#272d2d", # black
  "#eb7aa8", # dark_red
  "#64c06a", # dark_green
  "#e9b64b", # dark_yellow
  "#91bcad", # dark_blue
  "#999fdb", # dark_magenta
  "#63bd89", # dark_cyan
  "#b2e5cd" # light_gray
]

brights = [
  "#51796d", # gray
  "#f08cb4", # red
  "#7fcd81", # green
  "#e2f776", # yellow
  "#c3eed9", # blue
  "#a5a9e5", # magenta
  "#81d6a5", # cyan
  "#d5f4e3" # white
]

[colors.tab_bar]
inactive_tab_edge = "#040606"
background = "#0c1010"

[colors.tab_bar.active_tab]
fg_color = "#0c1010"
bg_color = "#e2f776"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#0c1010"
bg_color = "#51796d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#0c1010"
bg_color = "#191e1e"

[colors.tab_bar.new_tab]
fg_color = "#0c1010"
bg_color = "#7fcd81"

[colors.tab_bar.new_tab_hover]
fg_color = "#0c1010"
bg_color = "#191e1e"
intensity = "Bold"
