background = #f2f5fc
foreground = #040089

selection-background = #dbdee5
selection-foreground = #040089

# Black
palette = 0=#153bb7
# Dark Red
palette = 1=#5a8fff
# Dark Green
palette = 2=#497cfd
# Dark Yellow
palette = 3=#497cfd
# Dark Blue
palette = 4=#5a8fff
# Dark Magenta
palette = 5=#497cfd
# Dark Cyan
palette = 6=#5a8fff
# Light Gray
palette = 7=#5a8fff

# Gray
palette = 8=#2955d3
# Red
palette = 9=#5a8fff
# Green
palette = 10=#497cfd
# Yellow
palette = 11=#497cfd
# Blue
palette = 12=#5a8fff
# Magenta
palette = 13=#497cfd
# Cyan
palette = 14=#5a8fff
# White
palette = 15=#5a8fff
