background = #f2e2ce
foreground = #2b2826

selection-background = #decfba
selection-foreground = #2b2826

# Black
palette = 0=#4e463d
# Dark Red
palette = 1=#c4b5a1
# Dark Green
palette = 2=#aa9c8a
# Dark Yellow
palette = 3=#aa9c8a
# Dark Blue
palette = 4=#c4b5a1
# Dark Magenta
palette = 5=#aa9c8a
# Dark Cyan
palette = 6=#c4b5a1
# Light Gray
palette = 7=#c4b5a1

# Gray
palette = 8=#7a7062
# Red
palette = 9=#c4b5a1
# Green
palette = 10=#aa9c8a
# Yellow
palette = 11=#aa9c8a
# Blue
palette = 12=#c4b5a1
# Magenta
palette = 13=#aa9c8a
# Cyan
palette = 14=#c4b5a1
# White
palette = 15=#c4b5a1
