background = #f2f5fc
foreground = #040089

selection-background = #dbdee5
selection-foreground = #040089

# Black
palette = 0=#153bb7
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#497cfd
# Dark Cyan
palette = 6=#5a8fff
# Light Gray
palette = 7=#5a8fff

# Gray
palette = 8=#2955d3
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#497cfd
# Cyan
palette = 14=#5a8fff
# White
palette = 15=#5a8fff
