background = #211f1c
foreground = #e8dccc

selection-background = #4e463d
selection-foreground = #e8dccc

# Black
palette = 0=#4e463d
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#9b9082
# Dark Cyan
palette = 6=#b4a99a
# Light Gray
palette = 7=#b4a99a

# Gray
palette = 8=#6c6154
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#9b9082
# Cyan
palette = 14=#b4a99a
# White
palette = 15=#b4a99a
