background = #152650
foreground = #ebf2ff

selection-background = #283b67
selection-foreground = #ebf2ff

# Black
palette = 0=#283b67
# Dark Red
palette = 1=#9eb7eb
# Dark Green
palette = 2=#8098ca
# Dark Yellow
palette = 3=#8098ca
# Dark Blue
palette = 4=#9eb7eb
# Dark Magenta
palette = 5=#8098ca
# Dark Cyan
palette = 6=#9eb7eb
# Light Gray
palette = 7=#9eb7eb

# Gray
palette = 8=#4d6291
# Red
palette = 9=#9eb7eb
# Green
palette = 10=#8098ca
# Yellow
palette = 11=#8098ca
# Blue
palette = 12=#9eb7eb
# Magenta
palette = 13=#8098ca
# Cyan
palette = 14=#9eb7eb
# White
palette = 15=#9eb7eb
