[metadata]
author = "Black Atom Industries"
name = "Black Atom — Minium ∷ Polymer Light"

[colors]
foreground = "#1d1d1d"
background = "#dbdbdb"
cursor_bg = "#f55d12"
cursor_border = "#f55d12"
cursor_fg = "#dbdbdb"
selection_bg = "#c4c4c4"
selection_fg = "#1d1d1d"
split = "#f55d12"
compose_cursor = "#f14d4c"
scrollbar_thumb = "#46474c"

ansi = [
  "#404040", # black
  "#939d9f", # dark_red
  "#757b80", # dark_green
  "#18171f", # dark_yellow
  "#939d9f", # dark_blue
  "#757b80", # dark_magenta
  "#939d9f", # dark_cyan
  "#939d9f" # light_gray
]

brights = [
  "#46474c", # gray
  "#939d9f", # red
  "#757b80", # green
  "#f55d12", # yellow
  "#939d9f", # blue
  "#757b80", # magenta
  "#939d9f", # cyan
  "#939d9f" # white
]

[colors.tab_bar]
inactive_tab_edge = "#cacacc"
background = "#dbdbdb"

[colors.tab_bar.active_tab]
fg_color = "#cacacc"
bg_color = "#f55d12"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#cacacc"
bg_color = "#c4c4c4"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#cacacc"
bg_color = "#cacacc"

[colors.tab_bar.new_tab]
fg_color = "#cacacc"
bg_color = "#819e00"

[colors.tab_bar.new_tab_hover]
fg_color = "#cacacc"
bg_color = "#cacacc"
intensity = "Bold"
