[metadata]
author = "Black Atom Industries"
name = "Black Atom — Minium ∷ Polymer Dark"

[colors]
foreground = "#cfcdcb"
background = "#252728"
cursor_bg = "#ff8352"
cursor_border = "#ff8352"
cursor_fg = "#252728"
selection_bg = "#404040"
selection_fg = "#cfcdcb"
split = "#ff8352"
compose_cursor = "#dd7577"
scrollbar_thumb = "#757b80"

ansi = [
  "#404040", # black
  "#939d9f", # dark_red
  "#757b80", # dark_green
  "#d0e1e9", # dark_yellow
  "#939d9f", # dark_blue
  "#757b80", # dark_magenta
  "#939d9f", # dark_cyan
  "#939d9f" # light_gray
]

brights = [
  "#46474c", # gray
  "#939d9f", # red
  "#757b80", # green
  "#ff8352", # yellow
  "#939d9f", # blue
  "#757b80", # magenta
  "#939d9f", # cyan
  "#939d9f" # white
]

[colors.tab_bar]
inactive_tab_edge = "#1d1d1d"
background = "#252728"

[colors.tab_bar.active_tab]
fg_color = "#252728"
bg_color = "#ff8352"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#252728"
bg_color = "#404040"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#252728"
bg_color = "#27292a"

[colors.tab_bar.new_tab]
fg_color = "#252728"
bg_color = "#a9ba78"

[colors.tab_bar.new_tab_hover]
fg_color = "#252728"
bg_color = "#27292a"
intensity = "Bold"
