background = #c3cfd4
foreground = #0f212d

cursor-color = #cc8f00
cursor-text = #c3cfd4

selection-background = #b4c3c9
selection-foreground = #0f212d

# Black
palette = 0=#2d404b
# Dark Red
palette = 1=#db5241
# Dark Green
palette = 2=#429c5a
# Dark Yellow
palette = 3=#cc8f00
# Dark Blue
palette = 4=#457ea1
# Dark Magenta
palette = 5=#a53c75
# Dark Cyan
palette = 6=#007980
# Light Gray
palette = 7=#7b919d

# Gray
palette = 8=#4c5d67
# Red
palette = 9=#db5241
# Green
palette = 10=#429c5a
# Yellow
palette = 11=#cc8f00
# Blue
palette = 12=#457ea1
# Magenta
palette = 13=#c65b93
# Cyan
palette = 14=#1c989e
# White
palette = 15=#a8b9c0
