local theme = {
    meta = {
        key = "black-atom-facility-dimmed-dark",
        label = "Black Atom — Facility ∷ Dimmed Dark",
        appearance = "dark",
        status = "release",
        collection = {
            key = "facility",
            label = "Facility",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#131717",
            d20 = "#1c2020",
            d30 = "#242a2a",
            d40 = "#333939",
            m10 = "#51796d",
            m20 = "#5b8972",
            m30 = "#75a490",
            m40 = "#91bcad",
            l10 = "#9bdebe",
            l20 = "#abe7ca",
            l30 = "#c1efd5",
            l40 = "#cef6de",
        },
        palette = {
            black = "#333939",
            gray = "#51796d",
            dark_red = "#eb7aa8",
            red = "#f08cb4",
            dark_green = "#5dba5d",
            green = "#80c980",
            dark_yellow = "#e9b565",
            yellow = "#dbee7a",
            dark_blue = "#91bcad",
            blue = "#abe7ca",
            dark_magenta = "#a2b0e0",
            magenta = "#b6bee0",
            dark_cyan = "#59bf84",
            cyan = "#75d69e",
            light_gray = "#9bdebe",
            white = "#c1efd5",
        },
        ui = {
            bg = {
                default = "#1c2020",
                panel = "#131717",
                float = "#131717",
                active = "#242a2a",
                disabled = "#51796d",
                hover = "#242a2a",
                selection = "#333939",
                search = "#333939",
                contrast = "#c1efd5",
                negative = "#6c4856",
                warn = "#636a44",
                info = "#53675d",
                hint = "#68563c",
                positive = "#445d44",
                add = "#445d44",
                delete = "#6c4856",
                modify = "#53675d",
            },
            fg = {
                default = "#c1efd5",
                subtle = "#91bcad",
                accent = "#dbee7a",
                disabled = "#75a490",
                contrast = "#1c2020",
                negative = "#f08cb4",
                warn = "#dbee7a",
                info = "#abe7ca",
                hint = "#e9b565",
                positive = "#80c980",
                add = "#80c980",
                delete = "#f08cb4",
                modify = "#abe7ca",
            },
        },
        syntax = {
            variable = {
                default = "#abe7ca",
                builtin = "#abe7ca",
                member = "#91bcad",
                parameter = "#e9b565",
            },
            property = {
                default = "#91bcad",
            },
            string = {
                default = "#80c980",
                doc = "#80c980",
                regexp = "#f08cb4",
                escape = "#f08cb4",
            },
            constant = {
                default = "#abe7ca",
                builtin = "#eb7aa8",
            },
            module = {
                default = "#91bcad",
            },
            boolean = {
                default = "#5dba5d",
            },
            number = {
                default = "#5dba5d",
            },
            type = {
                default = "#75d69e",
                builtin = "#59bf84",
            },
            attribute = {
                default = "#e9b565",
                builtin = "#e9b565",
            },
            func = {
                default = "#dbee7a",
                builtin = "#dbee7a",
                method = "#dbee7a",
            },
            constructor = {
                default = "#dbee7a",
            },
            keyword = {
                default = "#b6bee0",
                import = "#f08cb4",
                export = "#f08cb4",
            },
            operator = {
                default = "#b6bee0",
            },
            punctuation = {
                default = "#9bdebe",
                delimiter = "#91bcad",
                bracket = "#9bdebe",
                special = "#9bdebe",
            },
            comment = {
                default = "#51796d",
                doc = "#5dba5d",
                todo = "#80c980",
                error = "#f08cb4",
                warn = "#dbee7a",
                info = "#abe7ca",
                hint = "#e9b565",
            },
            markup = {
                heading = {
                    h1 = "#dbee7a",
                    h2 = "#dbee7a",
                    h3 = "#dbee7a",
                    h4 = "#9bdebe",
                    h5 = "#9bdebe",
                    h6 = "#9bdebe",
                },
                strong = "#dbee7a",
                italic = "#dbee7a",
                strikethrough = "#dbee7a",
                quote = "#80c980",
                math = "#5dba5d",
                link = "#80c980",
                list = {
                    default = "#9bdebe",
                    checked = "#80c980",
                    unchecked = "#9bdebe",
                },
                code = {
                    fg = "#91bcad",
                    bg = "#333939",
                },
            },
            tag = {
                default = "#dbee7a",
                builtin = "#e9b565",
                attribute = "#91bcad",
                delimiter = "#9bdebe",
            },
        },
    },
}

require("black-atom").load(theme)
