local theme = {
    meta = {
        key = "black-atom-minium-polymer-dark",
        label = "Black Atom — Minium ∷ Polymer Dark",
        appearance = "dark",
        status = "development",
        collection = {
            key = "minium",
            label = "Minium",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#1d1d1d",
            d20 = "#252728",
            d30 = "#27292a",
            d40 = "#404040",
            m10 = "#46474c",
            m20 = "#5b6168",
            m30 = "#757b80",
            m40 = "#939d9f",
            l10 = "#b1b1b1",
            l20 = "#bbbbb8",
            l30 = "#cfcdcb",
            l40 = "#ebebeb",
        },
        palette = {
            black = "#404040",
            gray = "#46474c",
            dark_red = "#939d9f",
            red = "#939d9f",
            dark_green = "#757b80",
            green = "#757b80",
            dark_yellow = "#d0e1e9",
            yellow = "#ff8352",
            dark_blue = "#939d9f",
            blue = "#939d9f",
            dark_magenta = "#757b80",
            magenta = "#757b80",
            dark_cyan = "#939d9f",
            cyan = "#939d9f",
            light_gray = "#939d9f",
            white = "#939d9f",
        },
        ui = {
            bg = {
                default = "#252728",
                panel = "#1d1d1d",
                float = "#1d1d1d",
                active = "#27292a",
                disabled = "#404040",
                hover = "#27292a",
                selection = "#404040",
                search = "#404040",
                contrast = "#b1b1b1",
                negative = "#643f3f",
                warn = "#60533f",
                info = "#40555d",
                hint = "#60533f",
                positive = "#505640",
                add = "#505640",
                delete = "#643f3f",
                modify = "#40555d",
            },
            fg = {
                default = "#cfcdcb",
                subtle = "#757b80",
                accent = "#ff8352",
                disabled = "#5b6168",
                contrast = "#252728",
                negative = "#dd7577",
                warn = "#d6b174",
                info = "#79b5cc",
                hint = "#d6b174",
                positive = "#a9ba78",
                add = "#a9ba78",
                delete = "#dd7577",
                modify = "#79b5cc",
            },
        },
        syntax = {
            variable = {
                default = "#bbbbb8",
                builtin = "#b1b1b1",
                member = "#d0e1e9",
                parameter = "#ebebeb",
            },
            property = {
                default = "#d0e1e9",
            },
            string = {
                default = "#bbbbb8",
                doc = "#b1b1b1",
                regexp = "#ebebeb",
                escape = "#ebebeb",
            },
            constant = {
                default = "#b1b1b1",
                builtin = "#bbbbb8",
            },
            module = {
                default = "#bbbbb8",
            },
            boolean = {
                default = "#939d9f",
            },
            number = {
                default = "#b1b1b1",
            },
            type = {
                default = "#ebebeb",
                builtin = "#ebebeb",
            },
            attribute = {
                default = "#d0e1e9",
                builtin = "#d0e1e9",
            },
            func = {
                default = "#ff8352",
                builtin = "#d0e1e9",
                method = "#d0e1e9",
            },
            constructor = {
                default = "#ff8352",
            },
            keyword = {
                default = "#d0e1e9",
                import = "#ebebeb",
                export = "#ebebeb",
            },
            operator = {
                default = "#cfcdcb",
            },
            punctuation = {
                default = "#b1b1b1",
                delimiter = "#b1b1b1",
                bracket = "#b1b1b1",
                special = "#b1b1b1",
            },
            comment = {
                default = "#757b80",
                doc = "#757b80",
                todo = "#a9ba78",
                error = "#dd7577",
                warn = "#d6b174",
                info = "#79b5cc",
                hint = "#79b5cc",
            },
            markup = {
                heading = {
                    h1 = "#ff8352",
                    h2 = "#ff8352",
                    h3 = "#ff8352",
                    h4 = "#939d9f",
                    h5 = "#939d9f",
                    h6 = "#939d9f",
                },
                strong = "#ff8352",
                italic = "#ff8352",
                strikethrough = "#ff8352",
                quote = "#5b6168",
                math = "#5b6168",
                link = "#d0e1e9",
                list = {
                    default = "#939d9f",
                    checked = "#a9ba78",
                    unchecked = "#939d9f",
                },
                code = {
                    fg = "#939d9f",
                    bg = "#404040",
                },
            },
            tag = {
                default = "#ff8352",
                builtin = "#d0e1e9",
                attribute = "#757b80",
                delimiter = "#b1b1b1",
            },
        },
    },
}

require("black-atom").load(theme)
