local theme = {
    meta = {
        key = "black-atom-jpn-sanshoku-light",
        label = "Black Atom — JPN ∷ Sanshoku Light",
        appearance = "light",
        status = "development",
        collection = {
            key = "jpn",
            label = "JPN",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#121b21",
            d20 = "#0f212d",
            d30 = "#1c2b34",
            d40 = "#2d404b",
            m10 = "#4c5d67",
            m20 = "#576975",
            m30 = "#617683",
            m40 = "#7b919d",
            l10 = "#a8b9c0",
            l20 = "#b4c3c9",
            l30 = "#c3cfd4",
            l40 = "#d2dbdf",
        },
        palette = {
            black = "#2d404b",
            gray = "#4c5d67",
            dark_red = "#b83022",
            red = "#db5241",
            dark_green = "#1d7d3e",
            green = "#429c5a",
            dark_yellow = "#ac6900",
            yellow = "#cc8f00",
            dark_blue = "#2b6083",
            blue = "#457ea1",
            dark_magenta = "#a53c75",
            magenta = "#c65b93",
            dark_cyan = "#007980",
            cyan = "#1c989e",
            light_gray = "#7b919d",
            white = "#a8b9c0",
        },
        ui = {
            bg = {
                default = "#c3cfd4",
                panel = "#b4c3c9",
                float = "#b4c3c9",
                active = "#d2dbdf",
                disabled = "#7b919d",
                hover = "#b4c3c9",
                selection = "#b4c3c9",
                search = "#b4c3c9",
                contrast = "#0f212d",
                negative = "#d6b1ab",
                warn = "#cebea7",
                info = "#abb9c2",
                hint = "#c6b4a3",
                positive = "#adc1b0",
                add = "#adc1b0",
                delete = "#d6b1ab",
                modify = "#abb9c2",
            },
            fg = {
                default = "#0f212d",
                subtle = "#617683",
                accent = "#cc8f00",
                disabled = "#7b919d",
                contrast = "#c3cfd4",
                negative = "#db5241",
                warn = "#cc8f00",
                info = "#457ea1",
                hint = "#ac6900",
                positive = "#429c5a",
                add = "#429c5a",
                delete = "#db5241",
                modify = "#457ea1",
            },
        },
        syntax = {
            variable = {
                default = "#457ea1",
                builtin = "#2b6083",
                member = "#a53c75",
                parameter = "#a53c75",
            },
            property = {
                default = "#457ea1",
            },
            string = {
                default = "#429c5a",
                doc = "#429c5a",
                regexp = "#db5241",
                escape = "#db5241",
            },
            constant = {
                default = "#2b6083",
                builtin = "#b83022",
            },
            module = {
                default = "#2b6083",
            },
            boolean = {
                default = "#1d7d3e",
            },
            number = {
                default = "#1d7d3e",
            },
            type = {
                default = "#1c989e",
                builtin = "#007980",
            },
            attribute = {
                default = "#ac6900",
                builtin = "#ac6900",
            },
            func = {
                default = "#cc8f00",
                builtin = "#cc8f00",
                method = "#cc8f00",
            },
            constructor = {
                default = "#cc8f00",
            },
            keyword = {
                default = "#c65b93",
                import = "#db5241",
                export = "#db5241",
            },
            operator = {
                default = "#2b6083",
            },
            punctuation = {
                default = "#4c5d67",
                delimiter = "#2b6083",
                bracket = "#4c5d67",
                special = "#4c5d67",
            },
            comment = {
                default = "#4c5d67",
                doc = "#1d7d3e",
                todo = "#429c5a",
                error = "#db5241",
                warn = "#cc8f00",
                info = "#457ea1",
                hint = "#ac6900",
            },
            markup = {
                heading = {
                    h1 = "#cc8f00",
                    h2 = "#cc8f00",
                    h3 = "#cc8f00",
                    h4 = "#4c5d67",
                    h5 = "#4c5d67",
                    h6 = "#4c5d67",
                },
                strong = "#cc8f00",
                italic = "#cc8f00",
                strikethrough = "#cc8f00",
                quote = "#429c5a",
                math = "#1d7d3e",
                link = "#429c5a",
                list = {
                    default = "#4c5d67",
                    checked = "#429c5a",
                    unchecked = "#4c5d67",
                },
                code = {
                    fg = "#4c5d67",
                    bg = "#a8b9c0",
                },
            },
            tag = {
                default = "#cc8f00",
                builtin = "#ac6900",
                attribute = "#4c5d67",
                delimiter = "#2d404b",
            },
        },
    },
}

require("black-atom").load(theme)
