local theme = {
    meta = {
        key = "black-atom-jpn-sanshoku-dark",
        label = "Black Atom — JPN ∷ Sanshoku Dark",
        appearance = "dark",
        status = "development",
        collection = {
            key = "jpn",
            label = "JPN",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#162f48",
            d20 = "#1d364f",
            d30 = "#233c56",
            d40 = "#2a435d",
            m10 = "#4f759c",
            m20 = "#5d84ac",
            m30 = "#6c93bc",
            m40 = "#8ab2dc",
            l10 = "#c2cad3",
            l20 = "#d2dae3",
            l30 = "#e2ebf3",
            l40 = "#f8fafd",
        },
        palette = {
            black = "#2a435d",
            gray = "#5d84ac",
            dark_red = "#d44c3b",
            red = "#f86c59",
            dark_green = "#50a465",
            green = "#6fc483",
            dark_yellow = "#d78c00",
            yellow = "#f8ac3d",
            dark_blue = "#5891da",
            blue = "#76b1fc",
            dark_magenta = "#c0558d",
            magenta = "#e274ab",
            dark_cyan = "#2ba1a7",
            cyan = "#53c1c7",
            light_gray = "#8ab2dc",
            white = "#c2cad3",
        },
        ui = {
            bg = {
                default = "#1d364f",
                panel = "#162f48",
                float = "#162f48",
                active = "#233c56",
                disabled = "#4f759c",
                hover = "#233c56",
                selection = "#2a435d",
                search = "#2a435d",
                contrast = "#e2ebf3",
                negative = "#7f4d44",
                warn = "#7d6240",
                info = "#4f647e",
                hint = "#715735",
                positive = "#4d6a53",
                add = "#4d6a53",
                delete = "#7f4d44",
                modify = "#4f647e",
            },
            fg = {
                default = "#e2ebf3",
                subtle = "#8ab2dc",
                accent = "#f8ac3d",
                disabled = "#6c93bc",
                contrast = "#1d364f",
                negative = "#f86c59",
                warn = "#f8ac3d",
                info = "#76b1fc",
                hint = "#d78c00",
                positive = "#6fc483",
                add = "#6fc483",
                delete = "#f86c59",
                modify = "#76b1fc",
            },
        },
        syntax = {
            variable = {
                default = "#d2dae3",
                builtin = "#8ab2dc",
                member = "#76b1fc",
                parameter = "#d78c00",
            },
            property = {
                default = "#76b1fc",
            },
            string = {
                default = "#6fc483",
                doc = "#6fc483",
                regexp = "#f86c59",
                escape = "#f86c59",
            },
            constant = {
                default = "#5891da",
                builtin = "#d44c3b",
            },
            module = {
                default = "#5891da",
            },
            boolean = {
                default = "#50a465",
            },
            number = {
                default = "#50a465",
            },
            type = {
                default = "#53c1c7",
                builtin = "#2ba1a7",
            },
            attribute = {
                default = "#d78c00",
                builtin = "#d78c00",
            },
            func = {
                default = "#f8ac3d",
                builtin = "#f8ac3d",
                method = "#f8ac3d",
            },
            constructor = {
                default = "#f8ac3d",
            },
            keyword = {
                default = "#f86c59",
                import = "#f86c59",
                export = "#f86c59",
            },
            operator = {
                default = "#5891da",
            },
            punctuation = {
                default = "#8ab2dc",
                delimiter = "#5891da",
                bracket = "#8ab2dc",
                special = "#8ab2dc",
            },
            comment = {
                default = "#5d84ac",
                doc = "#50a465",
                todo = "#6fc483",
                error = "#f86c59",
                warn = "#f8ac3d",
                info = "#76b1fc",
                hint = "#d78c00",
            },
            markup = {
                heading = {
                    h1 = "#f8ac3d",
                    h2 = "#f8ac3d",
                    h3 = "#f8ac3d",
                    h4 = "#8ab2dc",
                    h5 = "#8ab2dc",
                    h6 = "#8ab2dc",
                },
                strong = "#f8ac3d",
                italic = "#f8ac3d",
                strikethrough = "#f8ac3d",
                quote = "#6fc483",
                math = "#50a465",
                link = "#6fc483",
                list = {
                    default = "#8ab2dc",
                    checked = "#6fc483",
                    unchecked = "#8ab2dc",
                },
                code = {
                    fg = "#8ab2dc",
                    bg = "#2a435d",
                },
            },
            tag = {
                default = "#f8ac3d",
                builtin = "#d78c00",
                attribute = "#8ab2dc",
                delimiter = "#c2cad3",
            },
        },
    },
}

require("black-atom").load(theme)
