local theme = {
    meta = {
        key = "black-atom-facility-dimmed-light",
        label = "Black Atom — Facility ∷ Dimmed Light",
        appearance = "light",
        status = "release",
        collection = {
            key = "facility",
            label = "Facility",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#22272f",
            d20 = "#2b3b33",
            d30 = "#384b42",
            d40 = "#425953",
            m10 = "#476a5f",
            m20 = "#517a65",
            m30 = "#669a84",
            m40 = "#77a494",
            l10 = "#d2d9d9",
            l20 = "#dee4e4",
            l30 = "#eaf0f0",
            l40 = "#f6fbfb",
        },
        palette = {
            black = "#425953",
            gray = "#476a5f",
            dark_red = "#b54567",
            red = "#cb4c7c",
            dark_green = "#358636",
            green = "#3f9640",
            dark_yellow = "#d7a537",
            yellow = "#a8ba33",
            dark_blue = "#517a65",
            blue = "#476a5f",
            dark_magenta = "#7062b8",
            magenta = "#8074bd",
            dark_cyan = "#15874d",
            cyan = "#009a52",
            light_gray = "#d2d9d9",
            white = "#eaf0f0",
        },
        ui = {
            bg = {
                default = "#eaf0f0",
                panel = "#dee4e4",
                float = "#dee4e4",
                active = "#d2d9d9",
                disabled = "#77a494",
                hover = "#d2d9d9",
                selection = "#d2d9d9",
                search = "#d2d9d9",
                contrast = "#2b3b33",
                negative = "#eac7d0",
                warn = "#dce2c5",
                info = "#c2cbc8",
                hint = "#e9dcc5",
                positive = "#c4d8c2",
                add = "#c4d8c2",
                delete = "#eac7d0",
                modify = "#c2cbc8",
            },
            fg = {
                default = "#2b3b33",
                subtle = "#669a84",
                accent = "#a8ba33",
                disabled = "#77a494",
                contrast = "#eaf0f0",
                negative = "#cb4c7c",
                warn = "#a8ba33",
                info = "#476a5f",
                hint = "#d7a537",
                positive = "#3f9640",
                add = "#3f9640",
                delete = "#cb4c7c",
                modify = "#476a5f",
            },
        },
        syntax = {
            variable = {
                default = "#476a5f",
                builtin = "#384b42",
                member = "#476a5f",
                parameter = "#d7a537",
            },
            property = {
                default = "#476a5f",
            },
            string = {
                default = "#3f9640",
                doc = "#3f9640",
                regexp = "#cb4c7c",
                escape = "#cb4c7c",
            },
            constant = {
                default = "#476a5f",
                builtin = "#b54567",
            },
            module = {
                default = "#517a65",
            },
            boolean = {
                default = "#358636",
            },
            number = {
                default = "#358636",
            },
            type = {
                default = "#009a52",
                builtin = "#15874d",
            },
            attribute = {
                default = "#d7a537",
                builtin = "#d7a537",
            },
            func = {
                default = "#a8ba33",
                builtin = "#a8ba33",
                method = "#a8ba33",
            },
            constructor = {
                default = "#a8ba33",
            },
            keyword = {
                default = "#8074bd",
                import = "#cb4c7c",
                export = "#cb4c7c",
            },
            operator = {
                default = "#8074bd",
            },
            punctuation = {
                default = "#476a5f",
                delimiter = "#77a494",
                bracket = "#476a5f",
                special = "#476a5f",
            },
            comment = {
                default = "#669a84",
                doc = "#358636",
                todo = "#3f9640",
                error = "#cb4c7c",
                warn = "#a8ba33",
                info = "#476a5f",
                hint = "#d7a537",
            },
            markup = {
                heading = {
                    h1 = "#a8ba33",
                    h2 = "#a8ba33",
                    h3 = "#a8ba33",
                    h4 = "#476a5f",
                    h5 = "#476a5f",
                    h6 = "#476a5f",
                },
                strong = "#a8ba33",
                italic = "#a8ba33",
                strikethrough = "#a8ba33",
                quote = "#3f9640",
                math = "#358636",
                link = "#3f9640",
                list = {
                    default = "#476a5f",
                    checked = "#3f9640",
                    unchecked = "#476a5f",
                },
                code = {
                    fg = "#476a5f",
                    bg = "#d2d9d9",
                },
            },
            tag = {
                default = "#a8ba33",
                builtin = "#d7a537",
                attribute = "#476a5f",
                delimiter = "#358636",
            },
        },
    },
}

require("black-atom").load(theme)
