local theme = {
    meta = {
        key = "black-atom-minium-polymer-light",
        label = "Black Atom — Minium ∷ Polymer Light",
        appearance = "light",
        status = "development",
        collection = {
            key = "minium",
            label = "Minium",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#0f0f11",
            d20 = "#1d1d1d",
            d30 = "#252728",
            d40 = "#404040",
            m10 = "#46474c",
            m20 = "#5b6168",
            m30 = "#757b80",
            m40 = "#939d9f",
            l10 = "#c4c4c4",
            l20 = "#cacacc",
            l30 = "#dbdbdb",
            l40 = "#ebebeb",
        },
        palette = {
            black = "#404040",
            gray = "#46474c",
            dark_red = "#939d9f",
            red = "#939d9f",
            dark_green = "#757b80",
            green = "#757b80",
            dark_yellow = "#18171f",
            yellow = "#f55d12",
            dark_blue = "#939d9f",
            blue = "#939d9f",
            dark_magenta = "#757b80",
            magenta = "#757b80",
            dark_cyan = "#939d9f",
            cyan = "#939d9f",
            light_gray = "#939d9f",
            white = "#939d9f",
        },
        ui = {
            bg = {
                default = "#dbdbdb",
                panel = "#cacacc",
                float = "#cacacc",
                active = "#ebebeb",
                disabled = "#c4c4c4",
                hover = "#cacacc",
                selection = "#c4c4c4",
                search = "#c4c4c4",
                contrast = "#404040",
                negative = "#f3c7c3",
                warn = "#e6d0bb",
                info = "#c0daec",
                hint = "#e6d0bb",
                positive = "#cfd8bc",
                add = "#cfd8bc",
                delete = "#f3c7c3",
                modify = "#c0daec",
            },
            fg = {
                default = "#1d1d1d",
                subtle = "#46474c",
                accent = "#f55d12",
                disabled = "#757b80",
                contrast = "#cacacc",
                negative = "#f14d4c",
                warn = "#cd7b00",
                info = "#00a3e9",
                hint = "#cd7b00",
                positive = "#819e00",
                add = "#819e00",
                delete = "#f14d4c",
                modify = "#00a3e9",
            },
        },
        syntax = {
            variable = {
                default = "#252728",
                builtin = "#404040",
                member = "#18171f",
                parameter = "#18171f",
            },
            property = {
                default = "#46474c",
            },
            string = {
                default = "#5b6168",
                doc = "#18171f",
                regexp = "#f55d12",
                escape = "#f55d12",
            },
            constant = {
                default = "#1d1d1d",
                builtin = "#0f0f11",
            },
            module = {
                default = "#252728",
            },
            boolean = {
                default = "#46474c",
            },
            number = {
                default = "#404040",
            },
            type = {
                default = "#0f0f11",
                builtin = "#404040",
            },
            attribute = {
                default = "#18171f",
                builtin = "#18171f",
            },
            func = {
                default = "#f55d12",
                builtin = "#18171f",
                method = "#18171f",
            },
            constructor = {
                default = "#f55d12",
            },
            keyword = {
                default = "#18171f",
                import = "#0f0f11",
                export = "#0f0f11",
            },
            operator = {
                default = "#1d1d1d",
            },
            punctuation = {
                default = "#404040",
                delimiter = "#404040",
                bracket = "#404040",
                special = "#404040",
            },
            comment = {
                default = "#5b6168",
                doc = "#5b6168",
                todo = "#819e00",
                error = "#f14d4c",
                warn = "#cd7b00",
                info = "#00a3e9",
                hint = "#00a3e9",
            },
            markup = {
                heading = {
                    h1 = "#f55d12",
                    h2 = "#f55d12",
                    h3 = "#f55d12",
                    h4 = "#46474c",
                    h5 = "#46474c",
                    h6 = "#46474c",
                },
                strong = "#f55d12",
                italic = "#f55d12",
                strikethrough = "#f55d12",
                quote = "#757b80",
                math = "#5b6168",
                link = "#18171f",
                list = {
                    default = "#46474c",
                    checked = "#819e00",
                    unchecked = "#46474c",
                },
                code = {
                    fg = "#46474c",
                    bg = "#c4c4c4",
                },
            },
            tag = {
                default = "#18171f",
                builtin = "#f55d12",
                attribute = "#46474c",
                delimiter = "#757b80",
            },
        },
    },
}

require("black-atom").load(theme)
