local theme = {
    meta = {
        key = "black-atom-facility-light",
        label = "Black Atom — Facility ∷ Light",
        appearance = "light",
        status = "release",
        collection = {
            key = "facility",
            label = "Facility",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#1e2229",
            d20 = "#2b3b33",
            d30 = "#384b42",
            d40 = "#425953",
            m10 = "#51796d",
            m20 = "#5b8972",
            m30 = "#75a490",
            m40 = "#95b8ac",
            l10 = "#e3e8e8",
            l20 = "#ecf1f1",
            l30 = "#f8f9f9",
            l40 = "#ffffff",
        },
        palette = {
            black = "#425953",
            gray = "#51796d",
            dark_red = "#b54567",
            red = "#cb4c7c",
            dark_green = "#358636",
            green = "#3f9640",
            dark_yellow = "#d7a537",
            yellow = "#a8ba33",
            dark_blue = "#5b8972",
            blue = "#51796d",
            dark_magenta = "#7062b8",
            magenta = "#8074bd",
            dark_cyan = "#15874d",
            cyan = "#009a52",
            light_gray = "#e3e8e8",
            white = "#f8f9f9",
        },
        ui = {
            bg = {
                default = "#f8f9f9",
                panel = "#ecf1f1",
                float = "#ecf1f1",
                active = "#e3e8e8",
                disabled = "#95b8ac",
                hover = "#e3e8e8",
                selection = "#e3e8e8",
                search = "#e3e8e8",
                contrast = "#2b3b33",
                negative = "#f2cfd8",
                warn = "#e4eacd",
                info = "#cdd8d4",
                hint = "#f1e4cd",
                positive = "#cce0ca",
                add = "#cce0ca",
                delete = "#f2cfd8",
                modify = "#cdd8d4",
            },
            fg = {
                default = "#2b3b33",
                subtle = "#75a490",
                accent = "#a8ba33",
                disabled = "#95b8ac",
                contrast = "#f8f9f9",
                negative = "#cb4c7c",
                warn = "#a8ba33",
                info = "#51796d",
                hint = "#d7a537",
                positive = "#3f9640",
                add = "#3f9640",
                delete = "#cb4c7c",
                modify = "#51796d",
            },
        },
        syntax = {
            variable = {
                default = "#51796d",
                builtin = "#384b42",
                member = "#51796d",
                parameter = "#d7a537",
            },
            property = {
                default = "#51796d",
            },
            string = {
                default = "#3f9640",
                doc = "#3f9640",
                regexp = "#cb4c7c",
                escape = "#cb4c7c",
            },
            constant = {
                default = "#51796d",
                builtin = "#b54567",
            },
            module = {
                default = "#5b8972",
            },
            boolean = {
                default = "#358636",
            },
            number = {
                default = "#358636",
            },
            type = {
                default = "#009a52",
                builtin = "#15874d",
            },
            attribute = {
                default = "#d7a537",
                builtin = "#d7a537",
            },
            func = {
                default = "#a8ba33",
                builtin = "#a8ba33",
                method = "#a8ba33",
            },
            constructor = {
                default = "#a8ba33",
            },
            keyword = {
                default = "#8074bd",
                import = "#cb4c7c",
                export = "#cb4c7c",
            },
            operator = {
                default = "#8074bd",
            },
            punctuation = {
                default = "#51796d",
                delimiter = "#95b8ac",
                bracket = "#51796d",
                special = "#51796d",
            },
            comment = {
                default = "#75a490",
                doc = "#358636",
                todo = "#3f9640",
                error = "#cb4c7c",
                warn = "#a8ba33",
                info = "#51796d",
                hint = "#d7a537",
            },
            markup = {
                heading = {
                    h1 = "#a8ba33",
                    h2 = "#a8ba33",
                    h3 = "#a8ba33",
                    h4 = "#51796d",
                    h5 = "#51796d",
                    h6 = "#51796d",
                },
                strong = "#a8ba33",
                italic = "#a8ba33",
                strikethrough = "#a8ba33",
                quote = "#3f9640",
                math = "#358636",
                link = "#3f9640",
                list = {
                    default = "#51796d",
                    checked = "#3f9640",
                    unchecked = "#51796d",
                },
                code = {
                    fg = "#51796d",
                    bg = "#e3e8e8",
                },
            },
            tag = {
                default = "#a8ba33",
                builtin = "#d7a537",
                attribute = "#51796d",
                delimiter = "#358636",
            },
        },
    },
}

require("black-atom").load(theme)
