local theme = {
    meta = {
        key = "black-atom-facility-dark",
        label = "Black Atom — Facility ∷ Dark",
        appearance = "dark",
        status = "release",
        collection = {
            key = "facility",
            label = "Facility",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#040606",
            d20 = "#0c1010",
            d30 = "#191e1e",
            d40 = "#272d2d",
            m10 = "#51796d",
            m20 = "#5b8972",
            m30 = "#75a490",
            m40 = "#91bcad",
            l10 = "#b2e5cd",
            l20 = "#c3eed9",
            l30 = "#d5f4e3",
            l40 = "#e8fbf0",
        },
        palette = {
            black = "#272d2d",
            gray = "#51796d",
            dark_red = "#eb7aa8",
            red = "#f08cb4",
            dark_green = "#64c06a",
            green = "#7fcd81",
            dark_yellow = "#e9b64b",
            yellow = "#e2f776",
            dark_blue = "#91bcad",
            blue = "#c3eed9",
            dark_magenta = "#999fdb",
            magenta = "#a5a9e5",
            dark_cyan = "#63bd89",
            cyan = "#81d6a5",
            light_gray = "#b2e5cd",
            white = "#d5f4e3",
        },
        ui = {
            bg = {
                default = "#0c1010",
                panel = "#040606",
                float = "#040606",
                active = "#191e1e",
                disabled = "#51796d",
                hover = "#191e1e",
                selection = "#272d2d",
                search = "#272d2d",
                contrast = "#d5f4e3",
                negative = "#5f3d4a",
                warn = "#596137",
                info = "#4f5e57",
                hint = "#5c4b2a",
                positive = "#395339",
                add = "#395339",
                delete = "#5f3d4a",
                modify = "#4f5e57",
            },
            fg = {
                default = "#d5f4e3",
                subtle = "#91bcad",
                accent = "#e2f776",
                disabled = "#75a490",
                contrast = "#0c1010",
                negative = "#f08cb4",
                warn = "#e2f776",
                info = "#c3eed9",
                hint = "#e9b64b",
                positive = "#7fcd81",
                add = "#7fcd81",
                delete = "#f08cb4",
                modify = "#c3eed9",
            },
        },
        syntax = {
            variable = {
                default = "#c3eed9",
                builtin = "#c3eed9",
                member = "#91bcad",
                parameter = "#e9b64b",
            },
            property = {
                default = "#91bcad",
            },
            string = {
                default = "#7fcd81",
                doc = "#7fcd81",
                regexp = "#f08cb4",
                escape = "#f08cb4",
            },
            constant = {
                default = "#c3eed9",
                builtin = "#eb7aa8",
            },
            module = {
                default = "#91bcad",
            },
            boolean = {
                default = "#64c06a",
            },
            number = {
                default = "#64c06a",
            },
            type = {
                default = "#81d6a5",
                builtin = "#63bd89",
            },
            attribute = {
                default = "#e9b64b",
                builtin = "#e9b64b",
            },
            func = {
                default = "#e2f776",
                builtin = "#e2f776",
                method = "#e2f776",
            },
            constructor = {
                default = "#e2f776",
            },
            keyword = {
                default = "#a5a9e5",
                import = "#f08cb4",
                export = "#f08cb4",
            },
            operator = {
                default = "#a5a9e5",
            },
            punctuation = {
                default = "#b2e5cd",
                delimiter = "#91bcad",
                bracket = "#b2e5cd",
                special = "#b2e5cd",
            },
            comment = {
                default = "#51796d",
                doc = "#64c06a",
                todo = "#7fcd81",
                error = "#f08cb4",
                warn = "#e2f776",
                info = "#c3eed9",
                hint = "#e9b64b",
            },
            markup = {
                heading = {
                    h1 = "#e2f776",
                    h2 = "#e2f776",
                    h3 = "#e2f776",
                    h4 = "#b2e5cd",
                    h5 = "#b2e5cd",
                    h6 = "#b2e5cd",
                },
                strong = "#e2f776",
                italic = "#e2f776",
                strikethrough = "#e2f776",
                quote = "#7fcd81",
                math = "#64c06a",
                link = "#7fcd81",
                list = {
                    default = "#b2e5cd",
                    checked = "#7fcd81",
                    unchecked = "#b2e5cd",
                },
                code = {
                    fg = "#91bcad",
                    bg = "#272d2d",
                },
            },
            tag = {
                default = "#e2f776",
                builtin = "#e9b64b",
                attribute = "#91bcad",
                delimiter = "#b2e5cd",
            },
        },
    },
}

require("black-atom").load(theme)
