local theme = {
    meta = {
        key = "black-atom-facility-dark",
        label = "Black Atom — Facility ∷ Dark",
        appearance = "dark",
        status = "release",
        collection = {
            key = "facility",
            label = "Facility",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#040606",
            d20 = "#0c1010",
            d30 = "#191e1e",
            d40 = "#272d2d",
            m10 = "#51796d",
            m20 = "#5b8972",
            m30 = "#75a490",
            m40 = "#91bcad",
            l10 = "#b2e5cd",
            l20 = "#c3eed9",
            l30 = "#d5f4e3",
            l40 = "#e8fbf0",
        },
        palette = {
            black = "#272d2d",
            gray = "#51796d",
            dark_red = "#ff93c1",
            red = "#ffa9d2",
            dark_green = "#7bd780",
            green = "#96e497",
            dark_yellow = "#f9c55c",
            yellow = "#e7fc7c",
            dark_blue = "#91bcad",
            blue = "#c3eed9",
            dark_magenta = "#b2b8f6",
            magenta = "#c3c8ff",
            dark_cyan = "#7ad49f",
            cyan = "#8ee4b2",
            light_gray = "#b2e5cd",
            white = "#d5f4e3",
        },
        ui = {
            bg = {
                default = "#0c1010",
                panel = "#040606",
                float = "#040606",
                active = "#191e1e",
                disabled = "#51796d",
                hover = "#191e1e",
                selection = "#272d2d",
                search = "#272d2d",
                contrast = "#d5f4e3",
                negative = "#644754",
                warn = "#5b6339",
                info = "#4f5e57",
                hint = "#62502f",
                positive = "#415a41",
                add = "#415a41",
                delete = "#644754",
                modify = "#4f5e57",
            },
            fg = {
                default = "#d5f4e3",
                subtle = "#91bcad",
                accent = "#e7fc7c",
                disabled = "#75a490",
                contrast = "#0c1010",
                negative = "#ffa9d2",
                warn = "#e7fc7c",
                info = "#c3eed9",
                hint = "#f9c55c",
                positive = "#96e497",
                add = "#96e497",
                delete = "#ffa9d2",
                modify = "#c3eed9",
            },
        },
        syntax = {
            variable = {
                default = "#c3eed9",
                builtin = "#c3eed9",
                member = "#91bcad",
                parameter = "#f9c55c",
            },
            property = {
                default = "#91bcad",
            },
            string = {
                default = "#96e497",
                doc = "#96e497",
                regexp = "#ffa9d2",
                escape = "#ffa9d2",
            },
            constant = {
                default = "#c3eed9",
                builtin = "#ff93c1",
            },
            module = {
                default = "#91bcad",
            },
            boolean = {
                default = "#7bd780",
            },
            number = {
                default = "#7bd780",
            },
            type = {
                default = "#8ee4b2",
                builtin = "#7ad49f",
            },
            attribute = {
                default = "#f9c55c",
                builtin = "#f9c55c",
            },
            func = {
                default = "#e7fc7c",
                builtin = "#e7fc7c",
                method = "#e7fc7c",
            },
            constructor = {
                default = "#e7fc7c",
            },
            keyword = {
                default = "#c3c8ff",
                import = "#ffa9d2",
                export = "#ffa9d2",
            },
            operator = {
                default = "#c3c8ff",
            },
            punctuation = {
                default = "#b2e5cd",
                delimiter = "#91bcad",
                bracket = "#b2e5cd",
                special = "#b2e5cd",
            },
            comment = {
                default = "#51796d",
                doc = "#7bd780",
                todo = "#96e497",
                error = "#ffa9d2",
                warn = "#e7fc7c",
                info = "#c3eed9",
                hint = "#f9c55c",
            },
            markup = {
                heading = {
                    h1 = "#e7fc7c",
                    h2 = "#e7fc7c",
                    h3 = "#e7fc7c",
                    h4 = "#b2e5cd",
                    h5 = "#b2e5cd",
                    h6 = "#b2e5cd",
                },
                strong = "#e7fc7c",
                italic = "#e7fc7c",
                strikethrough = "#e7fc7c",
                quote = "#96e497",
                math = "#7bd780",
                link = "#96e497",
                list = {
                    default = "#b2e5cd",
                    checked = "#96e497",
                    unchecked = "#b2e5cd",
                },
                code = {
                    fg = "#91bcad",
                    bg = "#272d2d",
                },
            },
            tag = {
                default = "#e7fc7c",
                builtin = "#f9c55c",
                attribute = "#91bcad",
                delimiter = "#b2e5cd",
            },
        },
    },
}

require("black-atom").load(theme)
