local theme = {
    meta = {
        key = "black-atom-default-light",
        label = "Black Atom — Light",
        appearance = "light",
        status = "release",
        collection = {
            key = "default",
            label = "Default",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#03060a",
            d20 = "#0e1217",
            d30 = "#1b2025",
            d40 = "#292e34",
            m10 = "#43484e",
            m20 = "#53595f",
            m30 = "#646a70",
            m40 = "#757b81",
            l10 = "#a8afb5",
            l20 = "#c8ced5",
            l30 = "#eff6fd",
            l40 = "#f6fdff",
        },
        palette = {
            black = "#0e1217",
            gray = "#43484e",
            dark_red = "#53595f",
            red = "#53595f",
            dark_green = "#757b81",
            green = "#757b81",
            dark_yellow = "#646a70",
            yellow = "#646a70",
            dark_blue = "#53595f",
            blue = "#53595f",
            dark_magenta = "#fb4583",
            magenta = "#6390fa",
            dark_cyan = "#11a22f",
            cyan = "#19b168",
            light_gray = "#757b81",
            white = "#a8afb5",
        },
        ui = {
            bg = {
                default = "#eff6fd",
                panel = "#c8ced5",
                float = "#c8ced5",
                active = "#f6fdff",
                disabled = "#a8afb5",
                hover = "#a8afb5",
                selection = "#a8afb5",
                search = "#a8afb5",
                contrast = "#292e34",
                negative = "#fee9ee",
                warn = "#fbecdf",
                info = "#deeced",
                hint = "#fbecdf",
                positive = "#deeedd",
                add = "#deeedd",
                delete = "#fee9ee",
                modify = "#deeced",
            },
            fg = {
                default = "#0e1217",
                subtle = "#43484e",
                accent = "#19b168",
                disabled = "#646a70",
                contrast = "#c8ced5",
                negative = "#fb80aa",
                warn = "#f29520",
                info = "#1c989e",
                hint = "#f29520",
                positive = "#11a22f",
                add = "#11a22f",
                delete = "#fb80aa",
                modify = "#1c989e",
            },
        },
        syntax = {
            variable = {
                default = "#292e34",
                builtin = "#292e34",
                member = "#53595f",
                parameter = "#fb4583",
            },
            property = {
                default = "#53595f",
            },
            string = {
                default = "#11a22f",
                doc = "#11a22f",
                regexp = "#11a22f",
                escape = "#11a22f",
            },
            constant = {
                default = "#292e34",
                builtin = "#1b2025",
            },
            module = {
                default = "#1b2025",
            },
            boolean = {
                default = "#11a22f",
            },
            number = {
                default = "#11a22f",
            },
            type = {
                default = "#19b168",
                builtin = "#11a22f",
            },
            attribute = {
                default = "#19b168",
                builtin = "#11a22f",
            },
            func = {
                default = "#1b2025",
                builtin = "#0e1217",
                method = "#0e1217",
            },
            constructor = {
                default = "#1b2025",
            },
            keyword = {
                default = "#6390fa",
                import = "#fb4583",
                export = "#fb4583",
            },
            operator = {
                default = "#1b2025",
            },
            punctuation = {
                default = "#292e34",
                delimiter = "#292e34",
                bracket = "#292e34",
                special = "#292e34",
            },
            comment = {
                default = "#757b81",
                doc = "#19b168",
                todo = "#11a22f",
                error = "#fb80aa",
                warn = "#f29520",
                info = "#1c989e",
                hint = "#1c989e",
            },
            markup = {
                heading = {
                    h1 = "#19b168",
                    h2 = "#19b168",
                    h3 = "#19b168",
                    h4 = "#292e34",
                    h5 = "#292e34",
                    h6 = "#292e34",
                },
                strong = "#19b168",
                italic = "#19b168",
                strikethrough = "#43484e",
                quote = "#53595f",
                math = "#53595f",
                link = "#19b168",
                list = {
                    default = "#43484e",
                    checked = "#11a22f",
                    unchecked = "#43484e",
                },
                code = {
                    fg = "#43484e",
                    bg = "#a8afb5",
                },
            },
            tag = {
                default = "#19b168",
                builtin = "#11a22f",
                attribute = "#43484e",
                delimiter = "#43484e",
            },
        },
    },
}

require("black-atom").load(theme)
