local theme = {
    meta = {
        key = "black-atom-facility-dimmed-dark",
        label = "Black Atom — Facility ∷ Dimmed Dark",
        appearance = "dark",
        status = "release",
        collection = {
            key = "facility",
            label = "Facility",
        },
    },
    colors = {
        none = "NONE",
        primaries = {
            d10 = "#131717",
            d20 = "#1c2020",
            d30 = "#242a2a",
            d40 = "#333939",
            m10 = "#51796d",
            m20 = "#5b8972",
            m30 = "#75a490",
            m40 = "#91bcad",
            l10 = "#9bdebe",
            l20 = "#abe7ca",
            l30 = "#c1efd5",
            l40 = "#cef6de",
        },
        palette = {
            black = "#333939",
            gray = "#51796d",
            dark_red = "#ff93c1",
            red = "#ffa9d2",
            dark_green = "#7bd780",
            green = "#96e497",
            dark_yellow = "#f9c55c",
            yellow = "#e7fc7c",
            dark_blue = "#91bcad",
            blue = "#abe7ca",
            dark_magenta = "#b2b8f6",
            magenta = "#c3c8ff",
            dark_cyan = "#7ad49f",
            cyan = "#8ee4b2",
            light_gray = "#9bdebe",
            white = "#c1efd5",
        },
        ui = {
            bg = {
                default = "#1c2020",
                panel = "#131717",
                float = "#131717",
                active = "#242a2a",
                disabled = "#51796d",
                hover = "#242a2a",
                selection = "#333939",
                search = "#333939",
                contrast = "#c1efd5",
                negative = "#705260",
                warn = "#676f45",
                info = "#53675d",
                hint = "#6e5c3a",
                positive = "#4c674c",
                add = "#4c674c",
                delete = "#705260",
                modify = "#53675d",
            },
            fg = {
                default = "#c1efd5",
                subtle = "#91bcad",
                accent = "#e7fc7c",
                disabled = "#75a490",
                contrast = "#1c2020",
                negative = "#ffa9d2",
                warn = "#e7fc7c",
                info = "#abe7ca",
                hint = "#f9c55c",
                positive = "#96e497",
                add = "#96e497",
                delete = "#ffa9d2",
                modify = "#abe7ca",
            },
        },
        syntax = {
            variable = {
                default = "#abe7ca",
                builtin = "#abe7ca",
                member = "#91bcad",
                parameter = "#f9c55c",
            },
            property = {
                default = "#91bcad",
            },
            string = {
                default = "#96e497",
                doc = "#96e497",
                regexp = "#ffa9d2",
                escape = "#ffa9d2",
            },
            constant = {
                default = "#abe7ca",
                builtin = "#ff93c1",
            },
            module = {
                default = "#91bcad",
            },
            boolean = {
                default = "#7bd780",
            },
            number = {
                default = "#7bd780",
            },
            type = {
                default = "#8ee4b2",
                builtin = "#7ad49f",
            },
            attribute = {
                default = "#f9c55c",
                builtin = "#f9c55c",
            },
            func = {
                default = "#e7fc7c",
                builtin = "#e7fc7c",
                method = "#e7fc7c",
            },
            constructor = {
                default = "#e7fc7c",
            },
            keyword = {
                default = "#c3c8ff",
                import = "#ffa9d2",
                export = "#ffa9d2",
            },
            operator = {
                default = "#c3c8ff",
            },
            punctuation = {
                default = "#9bdebe",
                delimiter = "#91bcad",
                bracket = "#9bdebe",
                special = "#9bdebe",
            },
            comment = {
                default = "#51796d",
                doc = "#7bd780",
                todo = "#96e497",
                error = "#ffa9d2",
                warn = "#e7fc7c",
                info = "#abe7ca",
                hint = "#f9c55c",
            },
            markup = {
                heading = {
                    h1 = "#e7fc7c",
                    h2 = "#e7fc7c",
                    h3 = "#e7fc7c",
                    h4 = "#9bdebe",
                    h5 = "#9bdebe",
                    h6 = "#9bdebe",
                },
                strong = "#e7fc7c",
                italic = "#e7fc7c",
                strikethrough = "#e7fc7c",
                quote = "#96e497",
                math = "#7bd780",
                link = "#96e497",
                list = {
                    default = "#9bdebe",
                    checked = "#96e497",
                    unchecked = "#9bdebe",
                },
                code = {
                    fg = "#91bcad",
                    bg = "#333939",
                },
            },
            tag = {
                default = "#e7fc7c",
                builtin = "#f9c55c",
                attribute = "#91bcad",
                delimiter = "#9bdebe",
            },
        },
    },
}

require("black-atom").load(theme)
