background = #002b51
foreground = #eef2f5

selection-background = #224c6a
selection-foreground = #eef2f5

# Black
palette = 0=#224c6a
# Dark Red
palette = 1=#a7bac9
# Dark Green
palette = 2=#839caf
# Dark Yellow
palette = 3=#839caf
# Dark Blue
palette = 4=#a7bac9
# Dark Magenta
palette = 5=#839caf
# Dark Cyan
palette = 6=#a7bac9
# Light Gray
palette = 7=#a7bac9

# Gray
palette = 8=#446883
# Red
palette = 9=#a7bac9
# Green
palette = 10=#839caf
# Yellow
palette = 11=#839caf
# Blue
palette = 12=#a7bac9
# Magenta
palette = 13=#839caf
# Cyan
palette = 14=#a7bac9
# White
palette = 15=#a7bac9
