background = #211f1c
foreground = #e8dccc

selection-background = #4e463d
selection-foreground = #e8dccc

# Black
palette = 0=#4e463d
# Dark Red
palette = 1=#b4a99a
# Dark Green
palette = 2=#9b9082
# Dark Yellow
palette = 3=#9b9082
# Dark Blue
palette = 4=#b4a99a
# Dark Magenta
palette = 5=#9b9082
# Dark Cyan
palette = 6=#b4a99a
# Light Gray
palette = 7=#b4a99a

# Gray
palette = 8=#6c6154
# Red
palette = 9=#b4a99a
# Green
palette = 10=#9b9082
# Yellow
palette = 11=#9b9082
# Blue
palette = 12=#b4a99a
# Magenta
palette = 13=#9b9082
# Cyan
palette = 14=#b4a99a
# White
palette = 15=#b4a99a
