background = #ede4cd
foreground = #201f1c

selection-background = #d9d0ba
selection-foreground = #201f1c

# Black
palette = 0=#4c473d
# Dark Red
palette = 1=#c0b7a1
# Dark Green
palette = 2=#a69e8a
# Dark Yellow
palette = 3=#a69e8a
# Dark Blue
palette = 4=#c0b7a1
# Dark Magenta
palette = 5=#a69e8a
# Dark Cyan
palette = 6=#c0b7a1
# Light Gray
palette = 7=#c0b7a1

# Gray
palette = 8=#777162
# Red
palette = 9=#c0b7a1
# Green
palette = 10=#a69e8a
# Yellow
palette = 11=#a69e8a
# Blue
palette = 12=#c0b7a1
# Magenta
palette = 13=#a69e8a
# Cyan
palette = 14=#c0b7a1
# White
palette = 15=#c0b7a1
