background = #332619
foreground = #dcd3c6

selection-background = #534537
selection-foreground = #dcd3c6

# Black
palette = 0=#534537
# Dark Red
palette = 1=#b1aa9f
# Dark Green
palette = 2=#9a9185
# Dark Yellow
palette = 3=#9a9185
# Dark Blue
palette = 4=#b1aa9f
# Dark Magenta
palette = 5=#9a9185
# Dark Cyan
palette = 6=#b1aa9f
# Light Gray
palette = 7=#b1aa9f

# Gray
palette = 8=#6e6152
# Red
palette = 9=#b1aa9f
# Green
palette = 10=#9a9185
# Yellow
palette = 11=#9a9185
# Blue
palette = 12=#b1aa9f
# Magenta
palette = 13=#9a9185
# Cyan
palette = 14=#b1aa9f
# White
palette = 15=#b1aa9f
