[metadata]
author = "Black Atom Industries"
name = "Black Atom — PAPER ∷ Blue Light"

[colors]
foreground = "#002469"
background = "#eff2f6"
cursor_bg = "#002469"
cursor_border = "#002469"
cursor_fg = "#eff2f6"
selection_bg = "#c5cbd2"
selection_fg = "#002469"
split = "#002469"
compose_cursor = "#f14d4c"
scrollbar_thumb = "#32669a"

ansi = [
  "#004f8b", # black
  "#679dd4", # dark_red
  "#558ac0", # dark_green
  "#558ac0", # dark_yellow
  "#679dd4", # dark_blue
  "#558ac0", # dark_magenta
  "#679dd4", # dark_cyan
  "#679dd4" # light_gray
]

brights = [
  "#32669a", # gray
  "#679dd4", # red
  "#558ac0", # green
  "#558ac0", # yellow
  "#679dd4", # blue
  "#558ac0", # magenta
  "#679dd4", # cyan
  "#679dd4" # white
]

[colors.tab_bar]
inactive_tab_edge = "#dadee3"
background = "#eff2f6"

[colors.tab_bar.active_tab]
fg_color = "#dadee3"
bg_color = "#002469"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#dadee3"
bg_color = "#c5cbd2"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#dadee3"
bg_color = "#dadee3"

[colors.tab_bar.new_tab]
fg_color = "#dadee3"
bg_color = "#819e00"

[colors.tab_bar.new_tab_hover]
fg_color = "#dadee3"
bg_color = "#dadee3"
intensity = "Bold"