background = #eff2f6
foreground = #002469

selection-background = #c5cbd2
selection-foreground = #002469

# Black
palette = 0=#004f8b
# Dark Red
palette = 1=#679dd4
# Dark Green
palette = 2=#558ac0
# Dark Yellow
palette = 3=#558ac0
# Dark Blue
palette = 4=#679dd4
# Dark Magenta
palette = 5=#558ac0
# Dark Cyan
palette = 6=#679dd4
# Light Gray
palette = 7=#679dd4

# Gray
palette = 8=#32669a
# Red
palette = 9=#679dd4
# Green
palette = 10=#558ac0
# Yellow
palette = 11=#558ac0
# Blue
palette = 12=#679dd4
# Magenta
palette = 13=#558ac0
# Cyan
palette = 14=#679dd4
# White
palette = 15=#679dd4
