background = #dbdbdb
foreground = #1d1d1d

cursor-color = #f55d12
cursor-text = #dbdbdb

selection-background = #c4c4c4
selection-foreground = #1d1d1d

# Black
palette = 0=#404040
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#757b80
# Dark Cyan
palette = 6=#939d9f
# Light Gray
palette = 7=#939d9f

# Gray
palette = 8=#46474c
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#757b80
# Cyan
palette = 14=#939d9f
# White
palette = 15=#939d9f
