background = #252728
foreground = #cfcdcb

cursor-color = #ff8352
cursor-text = #252728

selection-background = #404040
selection-foreground = #cfcdcb

# Black
palette = 0=#404040
# Dark Red
palette = 1=#dd7577
# Dark Green
palette = 2=#a9ba78
# Dark Yellow
palette = 3=#d6b174
# Dark Blue
palette = 4=#79b5cc
# Dark Magenta
palette = 5=#757b80
# Dark Cyan
palette = 6=#939d9f
# Light Gray
palette = 7=#939d9f

# Gray
palette = 8=#46474c
# Red
palette = 9=#dd7577
# Green
palette = 10=#a9ba78
# Yellow
palette = 11=#d6b174
# Blue
palette = 12=#79b5cc
# Magenta
palette = 13=#757b80
# Cyan
palette = 14=#939d9f
# White
palette = 15=#939d9f
