
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getConfig() : Promise<Config> {
    return await TAURI_INVOKE("get_config");
},
async saveConfig(config: Config) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Per-adapter setup state: provisioning class, the config fields its
 * updater reads, and whether its Linked placement is wired on disk.
 */
async getAppStatus() : Promise<AppStatus[]> {
    return await TAURI_INVOKE("get_app_status");
},
/**
 * Wire an adapter's own themes location to the unpacked theme files via
 * symlinks (create, heal, prune). Explicit adapter-setup action. The
 * target dir is derived from the adapter's CONFIGURED config_path (its
 * sibling `themes/`; for obsidian that is `<vault>/.obsidian/themes/`),
 * so custom setups link into the right place.
 */
async linkAppThemes(app: AppName) : Promise<LinkThemesResult> {
    return await TAURI_INVOKE("link_app_themes", { app });
},
/**
 * Conservative app detection: an app counts as found iff its configured
 * config file exists on disk. No binary lookups, no alternative-path
 * guessing (wizard territory, #35) — better to miss than misconfigure.
 */
async detectApps() : Promise<AppDetection[]> {
    return await TAURI_INVOKE("detect_apps");
},
/**
 * Single entry point for all app updates. The frontend calls this once per app.
 * 
 * Each invocation reads config from disk independently — this is inherent to the
 * Tauri IPC model where each `invoke` call is a separate request. At the current
 * scale (~5 apps, tiny JSON file) this is fine.
 */
async updateApp(app: AppName, theme: ThemeContext) : Promise<UpdateResult> {
    return await TAURI_INVOKE("update_app", { app, theme });
},
/**
 * Toggle system-wide dark/light mode. Separate from update_app because system
 * appearance is not an app with AppConfig — it's a standalone boolean toggle.
 */
async updateSystemAppearance(appearance: string) : Promise<UpdateResult> {
    return await TAURI_INVOKE("update_system_appearance", { appearance });
},
/**
 * Check one adapter's config_path: does it exist, and does its
 * match_pattern hit? Read-only — never writes.
 */
async verifyAppPath(app: AppName) : Promise<AppPathVerification> {
    return await TAURI_INVOKE("verify_app_path", { app });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * A config field an adapter's updater actually reads. Drives which inputs
 * the settings UI offers per adapter — editing a field the updater ignores
 * is silent noise; editing one it does read, wrongly, breaks switching.
 */
export type AdapterEditableField = "config_path" | "themes_path" | "match_pattern" | "replace_template"
export type AppConfig = { enabled?: boolean; config_path: string; themes_path?: string | null; match_pattern?: string | null; replace_template?: string | null }
/**
 * One adapter's detection outcome — backs the settings AUTO-DETECT action.
 */
export type AppDetection = { app: AppName; 
/**
 * The expanded path that was checked (empty = nothing to check).
 */
config_path: string; found: boolean }
/**
 * Supported app names. TypeScript bindings are auto-generated via tauri-specta.
 */
export type AppName = "nvim" | "tmux" | "ghostty" | "zed" | "delta" | "lazygit" | "herdr" | "obsidian" | "helm-tmux"
/**
 * Result of `verify_app_path` — backs the settings screen's [ VERIFY PATH ].
 */
export type AppPathVerification = { app: string; exists: boolean; 
/**
 * `Some(hit)` when the adapter has a match_pattern to check; `None` for
 * structural patchers (YAML/JSONC merge) where existence is the whole check.
 */
pattern_matches: boolean | null; 
/**
 * Why verification itself could not run (bad regex, unreadable file).
 */
message?: string | null }
/**
 * One adapter's setup state: which class it belongs to, which config fields
 * its updater reads, and whether its Linked placement is wired on disk.
 */
export type AppStatus = { app: AppName; 
/**
 * Who consumes the managed theme files — drives the class-specific
 * settings row content and the SET UP chain.
 */
provisioning: ThemeProvisioning; 
/**
 * Config fields this adapter's updater actually reads — trims the
 * settings field grid to what's safe to edit.
 */
editable_fields: AdapterEditableField[]; 
/**
 * The adapter's placement resolves to the managed themes dir right now.
 * Always `false` for External and Merged adapters, which have no
 * placement to wire.
 */
linked: boolean }
export type Config = { system_appearance: boolean; keymappings?: Keymappings; apps: { [key in AppName]: AppConfig } }
export type Keymappings = { toggle_window: string }
/**
 * Outcome of wiring one adapter's themes dir via managed symlinks.
 */
export type LinkThemesResult = { app: string; status: UpdateStatus; message?: string | null; linked: number | null; pruned: number | null }
/**
 * Theme metadata passed from the frontend.
 */
export type ThemeContext = { theme_key: string; appearance: string; collection_key: string; theme_label: string | null }
/**
 * Theme provisioning — who consumes the managed theme files (see ADAPTERS.md).
 * 
 * - `External`: the app's theme files are provided outside of livery (plugin,
 * compiled binary, or the user), so livery only performs switching.
 * - `Linked`: livery symlinks the unpacked theme files into a location the app
 * itself reads; switching selects one via a pointer in the app's config.
 * - `Merged`: the app cannot read external theme files, so on every switch
 * livery reads the unpacked theme file and writes its values into the config.
 */
export type ThemeProvisioning = "external" | "linked" | "merged"
export type UpdateResult = { app: string; status: UpdateStatus; message?: string | null; 
/**
 * Time taken by the updater in milliseconds.
 * Set by the dispatcher, not by individual updaters.
 */
duration_ms: number | null }
export type UpdateStatus = "done" | "error" | "skipped"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
