[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light"

[colors]
foreground = "#0e1217"
background = "#eff6fd"
cursor_bg = "#19b168"
cursor_border = "#19b168"
cursor_fg = "#eff6fd"
selection_bg = "#a8afb5"
selection_fg = "#0e1217"
split = "#19b168"
compose_cursor = "#fb80aa"
scrollbar_thumb = "#43484e"

ansi = [
  "#0e1217", # black
  "#53595f", # dark_red
  "#757b81", # dark_green
  "#646a70", # dark_yellow
  "#53595f", # dark_blue
  "#fb4583", # dark_magenta
  "#11a22f", # dark_cyan
  "#757b81" # light_gray
]

brights = [
  "#43484e", # gray
  "#53595f", # red
  "#757b81", # green
  "#646a70", # yellow
  "#53595f", # blue
  "#6390fa", # magenta
  "#19b168", # cyan
  "#a8afb5" # white
]

[colors.tab_bar]
inactive_tab_edge = "#c8ced5"
background = "#eff6fd"

[colors.tab_bar.active_tab]
fg_color = "#c8ced5"
bg_color = "#19b168"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#c8ced5"
bg_color = "#a8afb5"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#c8ced5"
bg_color = "#a8afb5"

[colors.tab_bar.new_tab]
fg_color = "#c8ced5"
bg_color = "#11a22f"

[colors.tab_bar.new_tab_hover]
fg_color = "#c8ced5"
bg_color = "#a8afb5"
intensity = "Bold"