background = #fff7f0
foreground = #38312b

selection-background = #e4dcd6
selection-foreground = #38312b

# Black
palette = 0=#4e463f
# Dark Red
palette = 1=#f14d4c
# Dark Green
palette = 2=#819e00
# Dark Yellow
palette = 3=#cd7b00
# Dark Blue
palette = 4=#00a3e9
# Dark Magenta
palette = 5=#897e74
# Dark Cyan
palette = 6=#988d83
# Light Gray
palette = 7=#988d83

# Gray
palette = 8=#6c6158
# Red
palette = 9=#f14d4c
# Green
palette = 10=#819e00
# Yellow
palette = 11=#cd7b00
# Blue
palette = 12=#00a3e9
# Magenta
palette = 13=#897e74
# Cyan
palette = 14=#988d83
# White
palette = 15=#988d83
