[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light"

[colors]
foreground = "#20252a"
background = "#eff6fd"
cursor_bg = "#2eaf6b"
cursor_border = "#2eaf6b"
cursor_fg = "#eff6fd"
selection_bg = "#d5dbe3"
selection_fg = "#20252a"
split = "#2eaf6b"
compose_cursor = "#ff50a7"
scrollbar_thumb = "#595e64"

ansi = [
  "#20252a", # black
  "#6a6f76", # dark_red
  "#8d9399", # dark_green
  "#7b8187", # dark_yellow
  "#6a6f76", # dark_blue
  "#df6989", # dark_magenta
  "#409d48", # dark_cyan
  "#8d9399" # light_gray
]

brights = [
  "#595e64", # gray
  "#6a6f76", # red
  "#8d9399", # green
  "#7b8187", # yellow
  "#6a6f76", # blue
  "#6791f1", # magenta
  "#2eaf6b", # cyan
  "#d5dbe3" # white
]

[colors.tab_bar]
inactive_tab_edge = "#e2e9f0"
background = "#eff6fd"

[colors.tab_bar.active_tab]
fg_color = "#e2e9f0"
bg_color = "#2eaf6b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#e2e9f0"
bg_color = "#d5dbe3"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#e2e9f0"
bg_color = "#d5dbe3"

[colors.tab_bar.new_tab]
fg_color = "#e2e9f0"
bg_color = "#00a800"

[colors.tab_bar.new_tab_hover]
fg_color = "#e2e9f0"
bg_color = "#d5dbe3"
intensity = "Bold"