background = #d8dfe6
foreground = #20252a

selection-background = #bec5cc
selection-foreground = #20252a

# Black
palette = 0=#20252a
# Dark Red
palette = 1=#6a6f76
# Dark Green
palette = 2=#8d9399
# Dark Yellow
palette = 3=#7b8187
# Dark Blue
palette = 4=#6a6f76
# Dark Magenta
palette = 5=#df6989
# Dark Cyan
palette = 6=#409d48
# Light Gray
palette = 7=#8d9399

# Gray
palette = 8=#595e64
# Red
palette = 9=#6a6f76
# Green
palette = 10=#8d9399
# Yellow
palette = 11=#7b8187
# Blue
palette = 12=#6a6f76
# Magenta
palette = 13=#6791f1
# Cyan
palette = 14=#2eaf6b
# White
palette = 15=#bec5cc
