[metadata]
author = "Black Atom Industries"
name = "Black Atom — Light Dimmed"

[colors]
foreground = "#20252a"
background = "#d8dfe6"
cursor_bg = "#2eaf6b"
cursor_border = "#2eaf6b"
cursor_fg = "#d8dfe6"
selection_bg = "#bec5cc"
selection_fg = "#20252a"
split = "#2eaf6b"
compose_cursor = "#ff50a7"
scrollbar_thumb = "#595e64"

ansi = [
  "#20252a", # black
  "#6a6f76", # dark_red
  "#8d9399", # dark_green
  "#7b8187", # dark_yellow
  "#6a6f76", # dark_blue
  "#5981e0", # dark_magenta
  "#409d48", # dark_cyan
  "#8d9399" # light_gray
]

brights = [
  "#595e64", # gray
  "#6a6f76", # red
  "#8d9399", # green
  "#7b8187", # yellow
  "#6a6f76", # blue
  "#8d85ed", # magenta
  "#2eaf6b", # cyan
  "#bec5cc" # white
]

[colors.tab_bar]
inactive_tab_edge = "#cbd2d9"
background = "#d8dfe6"

[colors.tab_bar.active_tab]
fg_color = "#cbd2d9"
bg_color = "#2eaf6b"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#cbd2d9"
bg_color = "#bec5cc"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#cbd2d9"
bg_color = "#bec5cc"

[colors.tab_bar.new_tab]
fg_color = "#cbd2d9"
bg_color = "#00a800"

[colors.tab_bar.new_tab_hover]
fg_color = "#cbd2d9"
bg_color = "#bec5cc"
intensity = "Bold"